name = "medicert-db"
main = "src/index.ts"
compatibility_date = "2024-11-01"
upload_source_maps = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_id = "4091baff-e770-4ee8-a0dd-613baf7947bd"
database_name = "pdf-india"

# Optional Smart Placement
# [placement]
# mode = "smart"

# Optional environment variables
# [vars]
# MY_VARIABLE = "production_value"

# Optional static assets
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Optional service bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
