name = "medshein-db"
main = "src/index.ts"
compatibility_date = "2024-11-01"
upload_source_maps = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_id = "907b1a12-f24c-4b6d-b4ce-a64dbc3623e4"
database_name = "medschein"

# Optional Smart Placement
# [placement]
# mode = "smart"

# Optional environment variables
# [vars]
# MY_VARIABLE = "production_value"

# Optional static assets
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Optional service bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
