name = "medshein-db"
main = "src/index.ts"
compatibility_date = "2024-11-01"
upload_source_maps = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_id = "151f7d9b-365f-41d7-83ed-0bf4eeef5086"
database_name = "d1-template-database"

# Optional Smart Placement
# [placement]
# mode = "smart"

# Optional environment variables
# [vars]
# MY_VARIABLE = "production_value"

# Optional static assets
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Optional service bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
